In [1]:
import numpy as np

## Dataypes & Attributes 

In [5]:
# NumPy's main datatype is ndarray ( n dimenasional)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
# axis 0 är rows, axis1 columns, axis N dimensions

In [12]:
a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(2, 3, 3)

In [15]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [16]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [17]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [18]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
#Create a datafrom from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [25]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [26]:
sample_array.dtype

dtype('int32')

In [28]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [31]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 0, 4, 8, 9],
       [8, 6, 1, 5, 7],
       [5, 0, 2, 0, 7]])

In [34]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.61053868, 0.46551016, 0.99369723],
       [0.89402275, 0.60816068, 0.11916892],
       [0.55812918, 0.3855219 , 0.62524514],
       [0.99940961, 0.50036743, 0.54239286],
       [0.34184197, 0.05977465, 0.47748523]])

In [35]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.27431967, 0.7996508 , 0.9509503 ],
       [0.49747803, 0.99114718, 0.91126654],
       [0.45823354, 0.7457986 , 0.53327799],
       [0.43182011, 0.48136769, 0.72618968],
       [0.32529208, 0.63849066, 0.82170913]])

In [46]:
#Pseudo-random numbers
np.random.seed(99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [50]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])