In [1]:
import numpy as np

## Dataypes & Attributes 

In [2]:
# NumPy's main datatype is ndarray ( n dimenasional)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
# axis 0 är rows, axis1 columns, axis N dimensions

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
#Create a datafrom from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[2, 1, 5, 9, 2],
       [5, 0, 0, 5, 2],
       [7, 3, 8, 6, 9]])

In [22]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.03028546, 0.79125006, 0.09418682],
       [0.99845436, 0.83687181, 0.45756104],
       [0.59043696, 0.02486451, 0.37901681],
       [0.76512446, 0.1809435 , 0.88257187],
       [0.09611261, 0.55803176, 0.67770067]])

In [23]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.58742286, 0.34812493, 0.99937263],
       [0.7784475 , 0.25798804, 0.97254885],
       [0.7502734 , 0.05361339, 0.22882297],
       [0.36842765, 0.98266178, 0.33788403],
       [0.38779625, 0.32972267, 0.38740665]])

In [24]:
#Pseudo-random numbers
np.random.seed(99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [25]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and Matrices

In [27]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [28]:
a1

array([1, 2, 3])

In [29]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a1[0]

1

In [34]:
a2.shape

(2, 3)

In [32]:
a2[0]

array([1. , 2. , 3.3])

In [35]:
a3.shape

(2, 3, 3)

In [33]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [37]:
a2[1]

array([4. , 5. , 6.5])

In [38]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [39]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [47]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 7, 4, 1, 2],
         [8, 5, 2, 9, 6],
         [2, 5, 7, 7, 5],
         [5, 6, 0, 6, 4]],

        [[6, 2, 6, 8, 7],
         [0, 5, 8, 9, 7],
         [7, 6, 2, 5, 6],
         [1, 9, 3, 4, 0]],

        [[3, 5, 6, 4, 0],
         [4, 1, 5, 2, 4],
         [8, 7, 5, 7, 5],
         [3, 7, 6, 2, 3]]],


       [[[1, 1, 8, 4, 2],
         [1, 7, 0, 8, 8],
         [1, 2, 3, 0, 1],
         [1, 5, 5, 6, 0]],

        [[9, 3, 2, 4, 2],
         [8, 4, 9, 0, 0],
         [2, 6, 3, 9, 5],
         [4, 6, 9, 9, 9]],

        [[4, 8, 2, 4, 6],
         [5, 3, 5, 2, 6],
         [4, 3, 2, 5, 9],
         [7, 5, 8, 5, 2]]]])

In [41]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [49]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

#Column 5 inte med nu. "Slice" 

array([[[[4, 7, 4, 1],
         [8, 5, 2, 9],
         [2, 5, 7, 7],
         [5, 6, 0, 6]],

        [[6, 2, 6, 8],
         [0, 5, 8, 9],
         [7, 6, 2, 5],
         [1, 9, 3, 4]],

        [[3, 5, 6, 4],
         [4, 1, 5, 2],
         [8, 7, 5, 7],
         [3, 7, 6, 2]]],


       [[[1, 1, 8, 4],
         [1, 7, 0, 8],
         [1, 2, 3, 0],
         [1, 5, 5, 6]],

        [[9, 3, 2, 4],
         [8, 4, 9, 0],
         [2, 6, 3, 9],
         [4, 6, 9, 9]],

        [[4, 8, 2, 4],
         [5, 3, 5, 2],
         [4, 3, 2, 5],
         [7, 5, 8, 5]]]])

## 4.Manipulating & Comparing Arrays
### Arithmetic (math equations)

In [50]:
a1

array([1, 2, 3])

In [51]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [52]:
a1 + ones

array([2., 3., 4.])

In [53]:
a1 - ones

array([0., 1., 2.])

In [54]:
a1 * ones

array([1., 2., 3.])

In [55]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [56]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [57]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [58]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [65]:
# a2 * a3 = Error: Could not be broadcast together with shapes (2,3)  (2,3,3)
# How to fix? How can we reshape a2 so it can be compatible with a3?
#"How to reshape numpy array"
#numpy.reshape(a, newshape, order='C')[source]


In [68]:
# a2 = np.reshape(a2, (2,3,-1))
# a2 * a3
# Rätt?


array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [69]:
a1 / ones

array([1., 2., 3.])

In [70]:
# Floor division //, removes the decimals. Rundar ner till heltal
a2 // a1

array([[[1., 0., 0.],
        [2., 1., 0.],
        [3., 1., 1.]],

       [[4., 2., 1.],
        [5., 2., 1.],
        [6., 3., 2.]]])

In [71]:
a2 ** 2 #power, upphöjt

array([[[ 1.  ],
        [ 4.  ],
        [10.89]],

       [[16.  ],
        [25.  ],
        [42.25]]])

In [72]:
np.square(a2)

array([[[ 1.  ],
        [ 4.  ],
        [10.89]],

       [[16.  ],
        [25.  ],
        [42.25]]])

In [73]:
a1 % 2 #modular, remainder

array([1, 0, 1], dtype=int32)

In [74]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [75]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])